FROM alpine:latest
MAINTAINER Robert Savage "robert@shadeblue.com"

ENV TZ=America/New_York

RUN apk update  \
&& apk  add     \
   bash   \
   git    \
   gcc    \
   g++    \
   make   \
   tree   \
   curl